name: Rentx CI
on: 
  push: 
    branches: ["main"]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use rentx Use Node.js node-version:[18.x]
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "., !node_modules"
        target: "~/app/rentalx"
    - name: Update API
      uses: appleboy/ssh-action@v1.0.0
      with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         key: ${{ secrets.SSH_KEY }}
         script: |
            cd ~/app/rentalx
            yarn ./node_modules/.bin/typeorm migration:run -d dist/shared/infra/typeorm/dataSource.js
            pm2 restart rentx
            
